#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Package secrets
###################################################################################################
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  appinsights-ikey: {{  required "secrets.appinsights.ikey is required" .Values.secrets.appinsights.ikey | b64enc }}
  mongodb-pwd: {{  required "secrets.mongo.pwd is required" .Values.secrets.mongo.pwd | b64enc }}
