# QA values for ingestion.
nameOverride: ingestion
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "info"
    reason: "new qa deploy"
    current: true
    resources:
      requests:
        cpu: 150m
        memory: 600Mi
      limits:
        cpu: 220m
        memory: 800Mi
