version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: on-failure
    command: bash
    ports:
      - "7080:80"
      - "7443:443"
    tty: true
    stdin_open: true
    environment:
     - NODE_ENV=development
     - CONNECTION_STRING=mongodb://packagedb:27017/local
     - COLLECTION_NAME=packages
     - LOG_LEVEL = "debug"
    networks:
      dronedelivery:
        aliases:
          - package
  mongo:
    image: mongo:3.5.6
    ports:
      - "27017:27017"
    networks:
      dronedelivery:
        aliases:
          - packagedb
networks:
  dronedelivery:
    external:
      name: dronedelivery
