# Production values for ingestion.
nameOverride: ingestion
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    telemetry:
      level: "error"
    reason: "new prod deploy"
    ingress:
      class: "nginx-prod"
    resources:
      requests:
        cpu: 150m
        memory: 600Mi
      limits:
        cpu: 300m
        memory: 800Mi
    autoscaling:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 50
