# Dev values for delivery.
nameOverride: delivery
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new dev deploy"
    current: true
    resources:
      requests:
        cpu: 80m
        memory: 350Mi
      limits:
        cpu: 130m
        memory: 500Mi
