##  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Dronescheduler allow egress traffic
###################################################################################################

{{- if .Values.networkPolicy.egress.enabled }}
{{- $fullname := include "dronescheduler.fullname" . | replace "." "" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname  }}-np-whitelist-egress-traffic
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dronescheduler.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: dronedelivery
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  policyTypes:
  - Egress
  egress:
  # allow egress traffic to kubedns
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
      namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- if .Values.networkPolicy.egress.external.enabled }}
  # allow egress traffic to all external resources except pods within the
  # cluster subnet
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - {{ required "networkPolicy.egress.external.clusterSubnetPrefix is required to enable external traffic" .Values.networkPolicy.egress.external.clusterSubnetPrefix }}
{{- else if .Values.networkPolicy.egress.allowAll }}
  - to: []
{{- end }}
{{ end }}
