#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Account service
###################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
    bc: shipping
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: account
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account
  labels:                 # In API version apps/v1beta2, .metadata.labels no longer default to .spec.template.metadata.labels. 
    app: account
    version: 0.1.0
    bc: shipping
spec:
  replicas: 1
  selector:                # In API version apps/v1beta2, .spec.selector no longer default to .spec.template.metadata.labels. 
    matchLabels:           # spec.selector is immutable after creation of the Deployment in apps/v1beta2.
      app: account         
  template:                # A Deployment may terminate Pods whose labels match the selector if their template is different from .spec.template
    metadata:
      labels:
        app: account
        version: 0.1.0
        bc: shipping
      annotations:
        commit: 
        team: accountservice
        imagecreationdate:
    spec:
      containers:
      - name: account
        image: dronedelivery.azurecr.io/mockaccountservice:0.1.0
        env:
        # Integration with l5d Daemon Sets
        # - name: NODE_NAME
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: spec.nodeName
        # - name: POD_IP
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.podIP
        # - name: http_proxy
        #   value: $(NODE_NAME):4140
        # - name: CORRELATION_HEADER
        #   value: l5d-ctx-trace
        ports:
        - name: service
          containerPort: 80
