#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: qa
  namespace: backend-qa
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 5Gi
    pods: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging
  namespace: backend-staging
spec:
  hard:
    cpu: "50"
    memory: 200Gi
    pods: "250"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod
  namespace: backend
spec:
  hard:
    cpu: "50"
    memory: 200Gi
    pods: "250"
