 #https://aka.ms/ai-k8s-rbac
 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   # "namespace" omitted since ClusterRoles are not namespaced
   name: appinsights-k8s-property-reader
 rules:
 - apiGroups: ["", "apps"]
   resources: ["pods", "nodes", "replicasets", "deployments"]
   verbs: ["get", "list"]
---
# actual binding to the role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appinsights-k8s-property-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: backend-dev
roleRef:
  kind: ClusterRole
  name: appinsights-k8s-property-reader
  apiGroup: rbac.authorization.k8s.io
