version: '3.4'

services:
  delivery:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dronescheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  deliveryscheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  thirdparty:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
