#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Delivery allow ingress traffic
###################################################################################################

{{- if .Values.networkPolicy.ingress.enabled }}
{{- $fullname := include "delivery.fullname" . | replace "." "" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname  }}-np-whitelist-ingress-traffic
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "delivery.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: dronedelivery
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          dd.fabrikam.com/egress-delivery: "true"
          app.kubernetes.io/component: backend
          app.kubernetes.io/part-of: dronedelivery
{{- if .Values.networkPolicy.ingress.externalSubnet.enabled }}
    - ipBlock:
        cidr: {{ required "networkPolicy.ingress.externalSubnet.subnetPrefix is required to enable allow traffic from" .Values.networkPolicy.ingress.externalSubnet.subnetPrefix }}
{{- else if .Values.networkPolicy.egress.allowAll }}
    - {}
{{- end }}
    ports:
    - protocol: {{ .Values.service.targetProtocol }}
      port: {{ .Values.service.targetPort }}
{{- end }}
