#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Delivery service identity
###################################################################################################
{{- $fullname := include "delivery.fullname" . | replace "." "" }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: {{ $fullname }}-identity
 annotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-delete-policy": hook-failed,before-hook-creation
  "helm.sh/hook-weight": "0"
spec:
 type: 0
 ResourceID: {{ .Values.identity.resourceid }}
 ClientID: {{ .Values.identity.clientid }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
 name: {{ $fullname }}-identity-binding
 annotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-delete-policy": hook-failed,before-hook-creation
  "helm.sh/hook-weight": "1"
spec:
 AzureIdentity: {{ $fullname }}-identity
 Selector: {{ $fullname }}
